# Generated by Django 3.1.7 on 2021-02-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsStories',
            fields=[
                ('story_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('story_headline', models.CharField(max_length=64)),
                ('date', models.DateField(max_length=100)),
                ('story_cat', models.CharField(choices=[('pol', 'Politics'), ('art', 'Art News'), ('tech', 'Technology News'), ('trivia', 'Trivial News')], max_length=10)),
                ('story_region', models.CharField(choices=[('uk', 'UK'), ('eu', 'European News'), ('w', 'World News')], max_length=10)),
                ('story_details', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.authors')),
            ],
        ),
    ]
