# Generated by Django 3.1.7 on 2021-03-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20210221_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstories',
            old_name='author',
            new_name='story_author',
        ),
        migrations.RenameField(
            model_name='newsstories',
            old_name='date',
            new_name='story_date',
        ),
    ]
